### ISSUE TITLE
Path 

### ISSUE THREAD

**Issue by mrHola21** [Jolumine/Password_Generator#1]
Change the paths in setup.py. everyone does not use windows and everyone wont clone the repo at the same location . and everyone does not have the same name xD

**Comment by Jolumine** [comment]
The only thing I can to is let the Paths Empty or is there a possibility to create a function which is doing it for each operating system to get the path of the image??

**Comment by mrHola21** [comment]
yes actually you can do that . python comes with a inbuild library named os . access it's os.path.join() method.

**Comment by Jolumine** [comment]
Yes I know that os ist built in and we can get path with it. But I did not know about this method thanks dude. I'll try to correct that.

**Comment by mrHola21** [comment]
just a tip.

    Use `os.name` to check whether it's a posix-compliant system.
    Use `sys.platform` to check whether it's a linux, cygwin, darwin, atheos, etc.
    Use `platform.system` if you don't believe the other sources.

**Comment by Jolumine** [comment]
Thanks I appreciate your help.
